"""
Pydantic request and response schemas for the Research Assistant API.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    """Payload for submitting a research query."""
    query: str = Field(
        ...,
        min_length=3,
        max_length=1500,
        description="The research question to be answered by the multi-agent system.",
        example="What is attention in transformers?"
    )
    top_k: int = Field(
        default=10,
        ge=1,
        le=30,
        description="Number of document chunks to retrieve.",
        example=10
    )
    max_iterations: Optional[int] = Field(
        default=None,
        ge=1,
        le=5,
        description="Optional override for maximum Critic-Synthesizer refinement iterations.",
        example=3
    )


class EvidenceItem(BaseModel):
    """A grounded piece of evidence extracted from a source paper."""
    id: int = Field(
        ...,
        description="1-based numerical index matching [Evidence N] citations in the answer text.",
        example=1
    )
    source: str = Field(
        ...,
        description="Title, section, or filename of the source document.",
        example="Attention Is All You Need"
    )
    arxiv_id: Optional[str] = Field(
        None,
        description="arXiv ID of the source paper if applicable.",
        example="1706.03762"
    )
    text: str = Field(
        ...,
        description="Verbatim quote or extracted passage from the source paper.",
        example="The dominant sequence transduction models are based on complex recurrent or convolutional neural networks..."
    )


class QueryResponse(BaseModel):
    """Structured response returned after full multi-agent synthesis."""
    query: str = Field(
        ...,
        description="Original user research question.",
        example="What is attention in transformers?"
    )
    answer: str = Field(
        ...,
        description="Synthesized, cited academic answer generated by the multi-agent pipeline.",
        example="Attention mechanisms in transformers map queries and key-value pairs to outputs [Evidence 1]..."
    )
    sources: List[str] = Field(
        default_factory=list,
        description="List of attributed source papers (e.g., arXiv IDs).",
        example=["1706.03762"]
    )
    citations: List[str] = Field(
        default_factory=list,
        description="Citations listed by the Synthesizer agent.",
        example=["[Evidence 1] Vaswani et al., 2017"]
    )
    citation_ids: List[int] = Field(
        default_factory=list,
        description="Indices of verified [Evidence N] citations used in the answer.",
        example=[1]
    )
    evidence: List[EvidenceItem] = Field(
        default_factory=list,
        description="Full text and source mapping for each verified evidence passage."
    )
    confidence: float = Field(
        ...,
        description="Critic Agent confidence score (0.0 to 1.0).",
        example=0.98
    )
    is_grounded: bool = Field(
        ...,
        description="True if the Critic Agent confirmed zero hallucinations.",
        example=True
    )
    missing_aspects: List[str] = Field(
        default_factory=list,
        description="Aspects or topics flagged as omitted by the Critic.",
        example=[]
    )
    hallucination_flags: List[str] = Field(
        default_factory=list,
        description="Unsupported statements detected by the Critic.",
        example=[]
    )
    reasoning_trace: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Chronological step-by-step reasoning trace across all agents."
    )
    iterations: int = Field(
        ...,
        description="Number of Critic-Synthesizer iterations executed.",
        example=1
    )
    latency_seconds: float = Field(
        ...,
        description="Total query execution time in seconds.",
        example=74.5
    )


class StreamEvent(BaseModel):
    """Event schema emitted via Server-Sent Events (SSE)."""
    step: str = Field(
        ...,
        description="Pipeline step identifier: retrieval, reader, synthesizer, critic, complete, or error.",
        example="retrieval"
    )
    message: str = Field(
        ...,
        description="Human-readable status update for the current step.",
        example="Retrieved 8 document chunks from FAISS + BM25."
    )
    data: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Step-specific payload (e.g., retrieved docs, extracted passages, complete response)."
    )


class HealthResponse(BaseModel):
    """System health and GPU VRAM occupancy status."""
    model_config = {"protected_namespaces": ()}

    status: str = Field(
        ...,
        description="Overall service health state ('healthy' or 'degraded').",
        example="healthy"
    )
    gpu_device_name: Optional[str] = Field(
        None,
        description="Active GPU model name detected by PyTorch.",
        example="NVIDIA RTX PRO 6000 Blackwell Server Edition MIG 1g.24gb"
    )
    gpu_memory_used_mb: Optional[float] = Field(
        None,
        description="VRAM currently allocated in megabytes.",
        example=7088.76
    )
    gpu_memory_total_mb: Optional[float] = Field(
        None,
        description="Total VRAM available on the GPU in megabytes.",
        example=24192.0
    )
    model_loaded: bool = Field(
        ...,
        description="True if Mistral-7B model and LoRA adapter are loaded in memory.",
        example=True
    )
    indices_loaded: bool = Field(
        ...,
        description="True if FAISS and BM25 hybrid indices are loaded in memory.",
        example=True
    )
    uptime_seconds: float = Field(
        ...,
        description="API server uptime in seconds.",
        example=345.2
    )


class MetricsResponse(BaseModel):
    """Serving telemetry and performance statistics."""
    total_queries_served: int = Field(
        ...,
        description="Total count of inference queries processed since server startup.",
        example=25
    )
    avg_latency_seconds: float = Field(
        ...,
        description="Mean response latency across all queries in seconds.",
        example=74.5
    )
    avg_confidence: float = Field(
        ...,
        description="Mean groundedness confidence score across all served queries (0.0 to 1.0).",
        example=0.98
    )
    grounded_rate_percent: float = Field(
        ...,
        description="Percentage of queries verified with 0 hallucinations by the Critic Agent.",
        example=96.0
    )
    total_errors: int = Field(
        ...,
        description="Count of uncaught errors or exceptions during inference.",
        example=0
    )


class HistoryItem(BaseModel):
    """Summary of a past query session."""
    timestamp: str = Field(
        ...,
        description="Date and time when the query was executed (YYYY-MM-DD HH:MM:SS).",
        example="2026-09-04 10:15:30"
    )
    query: str = Field(
        ...,
        description="The submitted research question.",
        example="What is attention in transformers?"
    )
    answer_snippet: str = Field(
        ...,
        description="Truncated preview of the synthesized answer.",
        example="Attention mechanisms in transformers map queries and key-value pairs..."
    )
    confidence: float = Field(
        ...,
        description="Critic Agent groundedness confidence score.",
        example=0.98
    )
    is_grounded: bool = Field(
        ...,
        description="Whether the answer was validated as grounded with zero hallucinations.",
        example=True
    )
    latency_seconds: float = Field(
        ...,
        description="Execution latency of this query in seconds.",
        example=75.1
    )
