"""
Academic Research Exporter — Phase 5.

Provides formatting utilities to export research assistant responses into:
1. Valid BibTeX entries (.bib) for LaTeX/Overleaf citations.
2. Formatted academic markdown reports (.md) for note-taking in Notion, Obsidian, or Word.
"""

import re
from datetime import datetime
from typing import List, Dict, Any, Optional


def generate_bibtex(sources: List[str], doc_metadata: Optional[List[Dict[str, Any]]] = None) -> str:
    """
    Generates standard BibTeX citation entries for all referenced arXiv sources.
    """
    entries = []
    seen_ids = set()

    # Create mapping from doc_metadata if available
    meta_lookup = {}
    if doc_metadata:
        for m in doc_metadata:
            aid = m.get("arxiv_id")
            if aid:
                meta_lookup[aid] = m

    for s in sources:
        # Extract arXiv ID: "arXiv:2301.00001" -> "2301.00001"
        m = re.search(r"(?:arXiv:)?(\d{4}\.\d{4,5}(?:v\d+)?)", s, re.IGNORECASE)
        arxiv_id = m.group(1) if m else s.replace("arXiv:", "").strip()

        if not arxiv_id or arxiv_id in seen_ids or arxiv_id.lower() == "unknown":
            continue
        seen_ids.add(arxiv_id)

        meta = meta_lookup.get(arxiv_id, {})
        title = meta.get("title", f"Research Paper on {arxiv_id}")
        authors = meta.get("authors", "ArXiv Researchers")
        
        # Estimate year from arxiv ID (YYMM.NNNNN)
        year = "20" + arxiv_id[:2] if len(arxiv_id) >= 4 and arxiv_id[:2].isdigit() else str(datetime.now().year)
        cite_key = f"arxiv_{arxiv_id.replace('.', '_')}"

        bib_entry = (
            f"@article{{{cite_key},\n"
            f"  title     = {{{title}}},\n"
            f"  author    = {{{authors}}},\n"
            f"  journal   = {{arXiv preprint arXiv:{arxiv_id}}},\n"
            f"  year      = {{{year}}},\n"
            f"  eprint    = {{{arxiv_id}}},\n"
            f"  archivePrefix = {{arXiv}},\n"
            f"  url       = {{https://arxiv.org/abs/{arxiv_id}}}\n"
            f"}}"
        )
        entries.append(bib_entry)

    if not entries:
        return (
            "% No external arXiv citations found in the synthesis.\n"
            "@misc{research_assistant_report,\n"
            f"  title = {{Research Assistant Synthesis: No arXiv Citations}},\n"
            f"  year  = {{{datetime.now().year}}}\n"
            "}"
        )

    header = (
        f"% BibTeX Bibliography generated by Multi-Agent Research Assistant\n"
        f"% Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    )
    return header + "\n\n".join(entries) + "\n"


def generate_markdown_report(
    query: str,
    answer: str,
    confidence: float,
    is_grounded: bool,
    sources: List[str],
    citations: Optional[List[str]] = None,
    reasoning_trace: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """
    Builds a comprehensive, publication-ready Markdown research report.
    """
    timestamp = datetime.now().strftime("%B %d, %Y - %H:%M:%S")
    status_emoji = "✅ Grounded" if is_grounded else "⚠️ Unverified"
    
    # Format sources list
    sources_section = ""
    if sources:
        sources_list = []
        for s in sorted(set(sources)):
            clean_id = re.sub(r"^arXiv:", "", s).strip()
            sources_list.append(f"- **[{s}](https://arxiv.org/abs/{clean_id})**")
        sources_section = "\n".join(sources_list)
    else:
        sources_section = "_No external papers cited._"

    # Format trace summary
    trace_section = ""
    if reasoning_trace:
        trace_lines = []
        for step in reasoning_trace:
            step_name = step.get("step", "unknown")
            trace_lines.append(f"- **{step_name.title()}**: {step}")
        trace_section = (
            "### Multi-Agent Pipeline Trace\n\n"
            + "\n".join(trace_lines)
            + "\n\n"
        )

    report = (
        f"# 📄 Academic Research Report\n\n"
        f"**Generated:** {timestamp}  \n"
        f"**Verification:** {status_emoji} | **Confidence Score:** `{confidence:.2f}`\n\n"
        f"---\n\n"
        f"## 📌 Research Question\n\n"
        f"> {query}\n\n"
        f"## 📝 Verified Academic Synthesis\n\n"
        f"{answer}\n\n"
        f"---\n\n"
        f"## 📚 Primary Citations & References\n\n"
        f"{sources_section}\n\n"
        f"---\n\n"
        f"{trace_section}"
        f"_Report generated by the Multi-Agent Research Assistant._\n"
    )
    return report
